ARG BASE_IMAGE=fiware/orion-ld:latest
FROM ${BASE_IMAGE}

ADD ./docker/debug/gdbinit gdbinit

RUN yum -y install gdb

ENTRYPOINT ["gdb", "-x", "gdbinit", "--args", "orionld", "-fg", "-multiservice", "-ngsiv1Autocast"]

EXPOSE 1026
